import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > <header className="flex flex-row justify-between w-full sm:px-6 py-5 bg-[#0E2647]">
          <Link href ="/"  className="text-white ml-10">Home</Link>
        <div>
          <Link href ="/todo" className="text-white mr-10">Timer and To-do List</Link>
        </div>
      </header>
        {children}

      <footer className="flex flex-row justify-between w-full sm:px-6 py-5 bg-[#0E2647] mt-20 text-[10px]">
        <p className="text-white">© 2025 WIT Hackathon | NVZ</p>
      </footer>
      </body>
    </html>
  );
}